### ISSUE TITLE
Obóz rebeliantów - błędy

### ISSUE THREAD

**Issue by gerard546** [orcwarrior/Czas_Zaplaty#112]
1. Carlson -
   -brak zapisu w dzienniku po pokonaniu Leafa w queście "Delikatna sprawa"
   (Kiedy ukończyliśmy quest z aligatorami u jacka to nam on znikał z dziennika zadań, mimo że mieliśmy się zgłosić po pancerz. U Carllsona za to jest tak, że quest dalej "wisi" ale nic w nim nie pisze, że mamy do niego przyjść po pancerz. Proszę do ujednolicić.)
2. Angus (albo on albo inny pirat)-
   -po zabiciu strażnika mostu przed każdą rozmową wspomina nam o tym, że "zginął członek SO i moje imię padło w tej sprawie", w trzecim rozdziale siedzi na plaży
3. Parvez -śpi na stojąco (najlepiej dodać łóżka do wieży...)
4. Hanis - jeśli został wygnany z obozu to z jakiej racji trenuje on koło Tarana?
5. Taran - nie powinien do nas mówić "Witaj, przyjacielu!".
6. Jack Aligator - po rozmowie z Quentinem mamy udać się do Jacka gdzie rozmowa rozpoczyna się tak:
   -Chyba go znalazłem w innym lepszym świcie
   -Zabiłeś jednego z nas (~hahaha)
7. Pacho - podczas misji Ruda Gomeza na sam koniec mamy zabić "potwora" - nazwijcie go sztyletnik, ponieważ w późniejszym etapie gry tak ten potwór został przez was nazwany

**Comment by gerard546** [comment]
Mogę dać save z tego 6 punktu, bo to koniecznie trzeba naprawić...

**Comment by Splash97** [comment]
6 punktu nie da się naprawić. Efekt dźwiękowy jest umieszczony tam gdzie powinien, ale odtwarza się już na początku dialogu. To już wina samego Gothica i nic z tym się nie zrobi.
