### ISSUE TITLE
Wilczy pomocnik (bug wzięty z forum)

### ISSUE THREAD

**Issue by gerard546** [orcwarrior/Czas_Zaplaty#117]
1. Wilczy pomocnik "Biały Kieł" nie jest do końca oteksturowany, posiada białe elementy.
2. Wilka można przywoływać kiedy się chce oraz go zabijać, dzięki czemu przy nauczonej umiejętności zdobywania kłów można mieć ich   nieskończenie wiele.
3. Podczas misji, w której mam się pozbyć kretoszczórów Snafa są one nietykalne dla mnie, jednak mój wilczy towarzysz może je zabić. Gdy zdobywam z nich potrzebne rzeczy nie mogę ukończyć misji.

**Comment by Adanos** [comment]
Niepotrzebnie tu Mark cokolwiek robiłeś, bo jedynie co wymaga przy wilku poprawki, to tekstura. Od dawna otrzymuje się 0 punktów doświadczenia za wilka i nie dostajemy jego trofeów. Będę musiał wycofać twoje poprawki stąd.

**Comment by CarnageMarkus** [comment]
Aha. Ok. Myślałem ze ciągle to nie zrobione. Nie mam moda w komputerze, ale mogę poprawić ta texture. Potrzebuje tylko modelu i texa. Ze skryptów wygląda na to, ze używa jakiś inny model

**Comment by Adanos** [comment]
Znalazłem to: https://mega.co.nz/#!YYAwTBCT!K-Qy6nnLpIrO0EC1Sa59h1ZHHIKJatv88ZkYCYac9Sg
Model jest w formacie *.mdm.

**Comment by CarnageMarkus** [comment]
zdekompilowalem model, ale używa textury wolf2_body_v0.tga, chyba wysłałeś mi złe textury.

**Comment by CarnageMarkus** [comment]
https://www.dropbox.com/s/2mrx9ru27gw9k3z/bia%C5%82y%20kie%C5%82%20-%20tekstury%2C%20mdm.zip?dl=0
Zrobione
![wolf](https://cloud.githubusercontent.com/assets/9625437/6280408/d4e15224-b8ac-11e4-8105-f78f56f4777b.PNG)

Uwaga , gothic bardzo nie fajnie renderuje textury z alfa. W Gothicu jest troche gorzej

**Comment by Adanos** [comment]
Tak wygląda w grze:
http://s10.ifotos.pl/img/bialykiel_wxqaqsp.jpg
