### ISSUE TITLE
Wywalanie z gry

### ISSUE THREAD

**Issue by Adanos** [orcwarrior/Czas_Zaplaty#129]
Włączyłem nową grę, pochodziłem sobie pogadałem z piratami, sprawdziłem towary u Rodneya i po chwili wywala z gry.

05:50 Info:  5 U:    Skript: PoisonTrigger>>SkyPresetChecker .... <zError.cpp,#462>
05:50 Info:  5 U:    Skript: PoisonTrigger>>CustomRainFX_Checker .... <zError.cpp,#462>
05:50 Info:  5 U:    Skript: PoisonTrigger>>SleepFX_WaitTillDestinationTimeCome .... <zError.cpp,#462>
05:50 Info:  5 U:    Skript: PoisonTrigger<<ObserveConsole .... <zError.cpp,#462>
05:50 Info:  5 U:    Skript: PoisonTrigger<<MirrorDamage .... <zError.cpp,#462>
05:50 Info:  5 U:    Skript: PoisonTrigger<<Icearmor_minus .... <zError.cpp,#462>
05:50 Info:  5 U:    Skript: PoisonTrigger<<Magicshield_minus .... <zError.cpp,#462>
05:50 Info:  5 U:    Skript: PoisonTrigger<<Curse_damage .... <zError.cpp,#462>
05:50 Info:  5 U:    Skript: PoisonTrigger<<poison_damage .... <zError.cpp,#462>
05:50 Info:  5 U:    Skript: PoisonTrigger<<party_check .... <zError.cpp,#462>
05:50 Info:  8 B:     TRIGGER: oCTriggerScript DAMAGE_TRIGGER triggered -> DAMAGE_TRIGGER_FUNC .... <oTrigger.cpp,#167>
05:50 Info:  8 B:     TRIGGER: oCTriggerScript COMPASS_TRIGGER triggered -> COMPASS_TRIGGER .... <oTrigger.cpp,#167>
05:50 Info:  5 C:     Shutting down MSS .... <zSndMSS.cpp,#554>
05:50 Info: 10 C:     done .... <zSndMSS.cpp,#577>
05:50 Info:  5 X:     EmergencyExit: Releasing all DirectX-Objects ... .... <zRndD3D_Render.cpp,#266>
05:50 Info:  5 X:     EmergencyExit: D3DXUninitialize done .... <zRndD3D_Render.cpp,#284>
05:50 Warn:  0 X:     [RND3D-Destructor]: Can't uninitialize D3DX Utility Library ! Error: D3DXERR_D3DXNOTSTARTEDYET .... <zRndD3D.h,#124>
05:50 Info:  5 X:     [RND3D-Destructor]: D3DXUninitialize done .... <zRndD3D_Render.cpp,#292>
05:51 Warn:  0 C:     lost focus, setting to windowed mode .... <zWin32.cpp,#1254>
05:51 Info:  5 X:     Vid_SetScreenMode: Setting New Mode... .... <zRndD3D_Vid.cpp,#577>
05:51 Warn:  0 ==    ===================================== UNHANDLED EXCEPTION OCCURED ====================================================== .... <zError.cpp,#467>
05:51 Warn:  0 ==    ============================================ CRASH INFOS: ============================================================== .... <zError.cpp,#467>
05:51 Warn:  0 GO    THIC 1.08k_mod, Parser Version: 50 .... <zError.cpp,#467>
05:51 Warn:  0 Us    er:  Grzegorz,  CPUType: 586,  Mem: 3982 MB total, 2012 MB free .... <zError.cpp,#467>
05:51 Warn:  0 Ca    mera: Pos(33156.9883/-3397.01904/12456.0039), At(-0.44402042/-0.0921817198/0.891262233) .... <zError.cpp,#467>

**Comment by gerard546** [comment]
![2](https://cloud.githubusercontent.com/assets/6259702/6092485/585b2d6c-aee1-11e4-94e5-8d4da979835e.JPG)
![1](https://cloud.githubusercontent.com/assets/6259702/6092486/587dbc24-aee1-11e4-9933-9e71cada35f1.JPG)


Przespałem się do północy, a później do rana i wywaliło mnie z gry.

**Comment by gerard546** [comment]
![1](https://cloud.githubusercontent.com/assets/6259702/6103437/a71e4006-b044-11e4-9513-d0411475977a.JPG)

Nie wiem czym to jest spowodowane, ale dzieje się tak gdy chce wczytać jakiś save po dłuższym czasie grania na kodach.

**Comment by Adanos** [comment]
Jak wywala z gry, to najlepiej by było, gdybyś dał log z zSpy.

**Comment by gerard546** [comment]
![1](https://cloud.githubusercontent.com/assets/6259702/6184504/df70e578-b362-11e4-89da-6d4b6915191b.PNG)

nawet do gry nie mogę wbić przez tego z Spy.exe.

[i] 00:34 Info:  3 B:     GAME: Loading file 'content\gothic.src or .dat' .... <oGame.cpp,#716>
[i] 00:34 Info:  5 U:    PAR: CONTENT\STORY\NEW_SKILLS.D : Parse... .... <zError.cpp,#462>
[i] 00:34 Info:  5 U:    PAR: CONTENT\_INTERN\CONSTANTS.D : Parse... .... <zError.cpp,#462>
[i] 00:34 Info:  5 U:    PAR: CONTENT\_INTERN\CLASSES.D : Parse... .... <zError.cpp,#462>
[i] 00:34 Info:  5 U:    PAR: CONTENT\_INTERN\MAGIC_INTERN.D : Parse... .... <zError.cpp,#462>
[i] 00:34 Info:  5 U:    PAR: CONTENT\_INTERN\COMPASS.D : Parse... .... <zError.cpp,#462>
[i] 00:34 Info:  5 U:    PAR: CONTENT\_INTERN\FLOATS32.D : Parse... .... <zError.cpp,#462>
[i] 00:34 Info:  5 U:    PAR: CONTENT\_INTERN\FLOAT32TOSTRING.D : Parse... .... <zError.cpp,#462>
[i] 00:34 Info:  5 U:    PAR: CONTENT\_INTERN\INTTOHEX.D : Parse... .... <zError.cpp,#462>
[F] 00:34 Fatal:-1 U:    PAR: Found no matching File : _INTERN\ENGINECLASSES\*.D ( line 56 ) .... <zParser.cpp,#599>
[i] 00:34 Info:  5 X:     Store Device: NVIDIA GeForce 7900 GT/GTO .... <zError.cpp,#462>

**Comment by CarnageMarkus** [comment]
.MRM to przecież skompilowane modele... czemu szuka je w sound ? :o

**Comment by Adanos** [comment]
Może dlatego, że dwa pliki były w Sound? :D
ITMI_SMITH_TONGS.MRM oraz ITRW_2H_ORCSTAFF_01.MRM - wywaliłem je stamtąd. Było skopiowane z data\meshes.

**Comment by Adanos** [comment]
chicken poprawił, trzeba jeszcze przetestować.
