### ISSUE TITLE
Rodney

### ISSUE THREAD

**Issue by Adanos** [orcwarrior/Czas_Zaplaty#130]
Rodney nie ma broni. Ma ustawiony 6 krąg magii. Kiedy dochodzi do walki, wyciąga jakiś czar (być może ognisty pocisk, nie wiem, bo po chwili wywaliło z gry, może to być jednak z innego powodu) lub walczy lagą. Zastanowić się nad bronią dla Rodneya.

**Comment by gerard546** [comment]
Działa. Można wywalić.
