### ISSUE TITLE
Znikające bryłki u handlarzy

### ISSUE THREAD

**Issue by Splash97** [orcwarrior/Czas_Zaplaty#140]
Sprzedałem kilka rzeczy Draxowi i zostało mu sporo rudy. Po kolejnym handlu z nim, nie miał rudy - to samo jest z Foxem. Funkcja usuwania itemów handlarzom znów strzela focha krótka mówiąc.

**Comment by gerard546** [comment]
U mnie wszystko działa. Dałem mu trochę bryłek, a jak za chwilę znów wszedłem handel miał tyle ile powinien mieć.
