### ISSUE TITLE
Hank zostaje po zabiciu orków

### ISSUE THREAD

**Issue by Splash97** [orcwarrior/Czas_Zaplaty#144]
Po zabiciu orków gdzie był Carlson, Rodney i Angus idą do obozu, ale Hank zostaje. Może najlepiej dodać do dialogu z Angusem mu funkcję Ai_GotoWP? To samo jest z Gestathem po przyprowadzeniu go do obozu - stoi przy Ablu.

**Comment by gerard546** [comment]
Teraz przy wersji 1.3.1 Rodney stoi przy ciałach orków, a Hank i Angus wracają do obozu. Całą ekipę można spotkać w obozie rebeliantów, a nie jak wcześniej jedn z nich udawał się na plażę.
