### ISSUE TITLE
Crashe podczas obrony Obozu Rebeliantów

### ISSUE THREAD

**Issue by Splash97** [orcwarrior/Czas_Zaplaty#177]
Coś mi się zdaje, że za crashe odpowiedzialne są PFXy. Gdy zablokowałem magów klawiszem F6, by nie mogli rzucać czarów, crash nie pojawił się ani razu.

**Comment by Adanos** [comment]
Przywrócę stary system walki. Zobaczymy, czy będzie to miało wpływ na crashe podczas ataku.
