### ISSUE TITLE
Nic się nie dzieje po pokonaniu strażników

### ISSUE THREAD

**Issue by Splash97** [orcwarrior/Czas_Zaplaty#178]
Problem polega na tym, że jeśli wszyscy strażnicy atakujący obóz rebeliantów zostaną pokonani, dalej nic się nie dzieje. Żaden NPC nie zagaduje.
Save : 
https://www.sendspace.com/file/a8a9gq

**Comment by Adanos** [comment]
Chyba też można to zamknąć. Testerzy nie zgłosili problemów z tym w wersji 1.3.
