### ISSUE TITLE
Brak muzyki po powrocie od nekromanty

### ISSUE THREAD

**Issue by Splash97** [orcwarrior/Czas_Zaplaty#185]
Wróciłem od nekromanty i muzyka ucichła.
Save : https://www.sendspace.com/file/0yfsr9

**Comment by Adanos** [comment]
Okazuje się, że 
"Brak muzyki związany jest z nazwami utworów w folderze. Z tego, co zauważyłem to walkom w bossami (do których należy ucieczka przed lawą) są przyporządkowane ponumerowane utwory - dla lawy tego utworu nie ma, jest pod inną nazwą i trzeba zmienić mu nazwę z CAVE_ESCAPE na BOSSFGT6_DAY_STD. Muzyka jednak nadal jest zepsuta, ponieważ zamiast ciszy będzie przygrywał w kółko ten utwór; na moje oko problemem jets ta zmienna BOSSFIGHT, która najpewniej nie zeruje po ucieczce. "

Tak więc należy zmienić nazwę utworu oraz dodać wyłączenie jej po teleportacji do nekromanty.
