### ISSUE TITLE
Moje bugi!

### ISSUE THREAD

**Issue by Psimgoth** [orcwarrior/Czas_Zaplaty#215]
Witam serdecznie pana Adanosa. Chciałbym krótko wyrazić swoją opinię na temat tej modyfikacji i napisać tu jakie błędy spotkały mnie w grze.

1; Modyfikacja na pierwszy rzut oka przyciąga. Wyborna ścieżka dźwiękowa tak samo jak i fabuła. Pomysł genialny!. Częściowo czuję się rozczarowany ze względu na dużą ilość błędów jakie mnie spotkały podczas przygody w czasie zapłaty.

- W grze zakładamy że grający w Czas Zapłaty może nie znać mapy to tak jakby zaczął grać w Czas zapłaty bez grania w Gothic 1. Zakładając ten fakt misja z nowymi rekrutami może okazać się cholernie trudna, nawet dla osób którzy znają mapę. Uważam że jeśli w grze byłby profesjonalny dubbing typu jak w Złotych Wrotach klimat o jedną ligę by wzrósł.

BUGI

1: Gdy będziemy próbować zasnąć na łóżku w głębi to automatycznie nas scrashuje
2: Gdy machamy mieczem na sprincie dwuręcznym zamiast ubywać nam podwójnie wytrzymałości, przywraca je nam. Ten bug działa tylko na dwuręcznych broniach.
3: Strażnik mówi żeby otworzyć bramę a jednak nic się nie dzieje
4: (moje ulubione) w pobliżu Guy'a (w starym obozie) jest cień który daje ponad 30k expa ;D.
5: zadanie zbuntować kopaczy czy jak to tam... jeżeli na początku nie przekona się Guya to misja się  buguje i fabuła nam staje.
6: Nie wiem czy to bug ale powiecie mi dlaczego lekka zbroja najemnika z gównianym naramiennikiem nie okrywającego ciała ma więcej obrony niż pancerz z skóry czarnego trolla? śmiesznie... i przykre. Sory ale to dla mnie jest żenujące
7:  Nie spotkałem się z tym czymś że wykonując zadanie w pełni szpieg gomeza zamiast wykonanych przechodzi do niewykonanych mimo że innego sposobu nie ma..

**Comment by Adanos** [comment]
Zamykam.
