### ISSUE TITLE
Crash po wejściu do labiryntu

### ISSUE THREAD

**Issue by Splash97** [orcwarrior/Czas_Zaplaty#221]
W końcu mam internet, więc się zaczyna :I 
Gdy trzeba udać się po truciznę dla Balama, mod się crashuje po wejściu do labiryntu.
Save : https://www.sendspace.com/file/krluvd

**Comment by Adanos** [comment]
Ale trucizna dla Balama jest u nekromanty, a nie w labiryncie.

**Comment by Splash97** [comment]
Tylko, że w Górniczej Dolinie, runa do jego siedziby nie działa :P Pojawia się wtedy napis : Nie możesz użyć tej runy tutaj!

**Comment by Adanos** [comment]
Tak, bo musisz iść do tej całej jaskini. :P

**Comment by Splash97** [comment]
https://www.sendspace.com/file/76kn5t

**Comment by Adanos** [comment]
Wydaje mi się, że jest to spowodowane tym, że mamy różne wersje. :D Najwidoczniej poprawiłem skryptami to kiedyś, ale jako że masz starą wersję skryptów w modzie, to cię wywala.

Testerzy przetestują to w nowej wersji i wtedy się upewnimy.
