### ISSUE TITLE
Cavalorn stoi przed wejściem do zamku

### ISSUE THREAD

**Issue by Splash97** [orcwarrior/Czas_Zaplaty#222]
Po wybiciu strażników w lochach, udajemy się do zamku, ale Cavalorn zatrzymuje się na WP OCC_BARONS_ENTRANCE_DOWNSTAIRS.

**Comment by Splash97** [comment]
Nie. Po walce i dialogu prowadzi do tego WP i zatrzymuje się. Dalej nic się nie dzieje.

**Comment by Adanos** [comment]
Masz zapis przed tym dialogiem? :D Wydaje mi się, że za mała odległość jest w skrypcie. Zamiast 200 bym spróbował dać 500.

**Comment by Splash97** [comment]
https://www.sendspace.com/file/kxpkij
Aha, i Gomeza trzeba usunąć xD

**Comment by Adanos** [comment]
Udało ci się popchnąć fabułę? Jeśli tak, to co zrobiłeś by Cavalorn zagadał? :D

**Comment by Splash97** [comment]
Nie, nie :D Chodzi mi to, że Gomez nadal jest w zamku. Reszta magnatów w sumie też. A przez to, że są wrogo nastawieni, wybiegają z sali i można ich pobić i zabić.

**Comment by Adanos** [comment]
Nie chodziło mi o Gomeza, tylko ogólnie czy ruszyłeś z fabułą czy stoisz w miejscu?

**Comment by Splash97** [comment]
Ze względu na npc obsługujące systemy na dachu na targowisku, zbliżenie się do wejścia do podziemi zamku jest niemożliwe.

**Comment by Adanos** [comment]
Ok. :D Ale nie udało ci się pogadać z Cavalornem?

**Comment by Splash97** [comment]
Nope :I

**Comment by Adanos** [comment]
Poprawione. Problemem było to, że nie uruchomił się dialog https://github.com/orcwarrior/Czas_Zaplaty/blob/master/Content/Story/MISSIONS/DIA_HUN_336_Cavalorn.d#L2490-L2523
Należy więc wrócić i porozmawiać z Cavalornem na WP: OCC_MERCS_HALLWAY_FRONT.

Gomez zmienia rutynę przed atakiem na SO. Zauważyłem, że piraci i Ratford nie podążali za Rickiem, teraz powinni do końca, tzn. do WP: OCC_LADDER_TOP. Aha, dalej nie wiem co dalej ma być, bo schodzę na dół, ale nigdzie się nie teleportuje. :| Więc nie pamiętam, czy tam jest wejście do labiryntu, czy nie.
