### ISSUE TITLE
Poprawić MusicSystem_GetTheme

### ISSUE THREAD

**Issue by Adanos** [orcwarrior/Czas_Zaplaty#226]
Podczas zmiany świata z World.zen na Labirynt.zen wywala z gry. Powodem jest to, że prawdopodobnie zonevobname jest nullem: https://github.com/orcwarrior/Czas_Zaplaty/blob/master/Content/AI/AI_Intern/MusicSystem_Func.d#L139

**Comment by Adanos** [comment]
W sumie to nawet wcześniej jest coś źle, a dokładnie tu https://github.com/orcwarrior/Czas_Zaplaty/blob/master/Content/AI/AI_Intern/MusicSystem_Func.d#L136 - podczas czytania adresu.

**Comment by orcwarrior** [comment]
Hmmm, może kwestia tego że ten świat tj. Labirynt.zen nie posiada zadnego obiektu z którego odtwarzała by się muzyka, znając siebie z tamtych lat robiłem to bardzo po macoszemu i jakiś null-check nie wchodzi w grę :D

**Comment by Adanos** [comment]
Też o tym pomyślałem, że nie ma w zenie tej strefy muzycznej. Z drugiej strony jak zacznie się nową grę w Labirynt.zen to nie wywala. Więc spróbujemy dodać muzykę do tego zena i zobaczyć, czy działa. :D

**Comment by Splash97** [comment]
Problem załatwiony.

**Comment by Adanos** [comment]
Problemem był brak w zenie musiczone.
