### ISSUE TITLE
Zwiększyć obronę piratom, gdy pomagają Carlsonowi

### ISSUE THREAD

**Issue by Adanos** [orcwarrior/Czas_Zaplaty#235]
Zwiększyć obronę piratom, gdy pomagają Carlsonowi, tak aby nie ginęli z rąk orków.

**Comment by Adanos** [comment]
Stwierdziłem, że zwiększę piratom obronę od początku gry.

**Comment by orcwarrior** [comment]
O ile dobrze pamietam to była metoda w stylu SetTimedAtt, i nawet była
gdzie-niegdzie używana, więc dla pewności mozna im zwiekszyć HP na parę
minut.

2015-02-05 15:17 GMT+01:00 Adanos <notifications@github.com>:
