### ISSUE TITLE
Walka (wersja 1.3.1)

### ISSUE THREAD

**Issue by gerard546** [orcwarrior/Czas_Zaplaty#238]
Zacytuję tutaj Adanosa:
"Dostałeś trochę inną wersję niż pozostali, chcę sprawdzić, który system walki jest mniej awaryjny."

Bardzo fajnie zabija się przeciwników. Oprócz przeciwnika, którego aktualnie mamy obranego za cel atakuję też tych obok niego. Niestety wadą jest tu to, że podczas machania mieczem zabijam przeciwników, którzy są za mną... 

Przykład: walczę z XYZ i ktoś atakuje mnie z tyłu i od razu umiera (jestem napakowany xD )...

**Comment by Adanos** [comment]
Zamykam. Aktualny system walki: https://github.com/orcwarrior/Czas_Zaplaty/issues/329
