### ISSUE TITLE
Bronie

### ISSUE THREAD

**Issue by gerard546** [orcwarrior/Czas_Zaplaty#244]
![1](https://cloud.githubusercontent.com/assets/6259702/6123871/fafe844c-b107-11e4-8f14-fca22a66ca58.JPG)

Po pierwsze - nagrody w postaci broni powinny być do wyboru.
Po drugie - natrafiłem na taki smaczek (patrz powyższy screen) (po relogu zmienia się na broń dwuręczna)
Po trzecie - recepty nie działają tak jak powinny

I najważniejszy bug:
Nie mając składników mogę wytworzyć broń za pomocą kamienia szlifierskiego.

**Comment by gerard546** [comment]
Po trzecie - recepty nie działają tak jak powinny
Po czwarte - Nie mają składników mogę wytworzyć broń za pomocą kamienia szlifierskiego

**Comment by Adanos** [comment]
Nie można już utworzyć broni za pomocą kamienia szlifierskiego.
