### ISSUE TITLE
Strażnik na plaży (start gry)

### ISSUE THREAD

**Issue by CarnageMarkus** [orcwarrior/Czas_Zaplaty#260]
Dodać mu jakieś mięso, albo jabłko do ekwipunku

**Comment by Adanos** [comment]
Hmm, a po co?

**Comment by CarnageMarkus** [comment]
Bo jak sie kogoś pobije to się oczekuje dropa, jest to początek gry a wiec wtedy to każdy oczekuje. Jest   label enhancement bo nie do końca potrzebne. Jak się będzie komuś chciało ...
