### ISSUE TITLE
Wywalanie z gry podczas wczytywania w Cave.zen

### ISSUE THREAD

**Issue by Adanos** [orcwarrior/Czas_Zaplaty#265]
Log:
http://pastebin.com/rpJeKHR7

**Comment by Splash97** [comment]
Chyba przyczyną są npc, które mają przedmioty handlarzy. W cavie nie ma handlarzy i chyba dostają samo powietrze do swojego ekwipunku.

**Comment by Adanos** [comment]
Też o tym pomyślałem. Będę musiał wywalić inicjowanie handlarzy w innych zenach poza World. Ale żeby zadziałała poprawka będzie trzeba zacząć grać od nowa. :|

**Comment by Splash97** [comment]
Problem może być z wejściem do jakiejś lokacji, w której się już było? A gdyby wejść do folderu z zapisem i usunąć NazwaŚwiata.sav? Może nie wynikną żadne komplikacje z tego, poza tym, że zabite potwory i zabrane przedmioty znów będą w tej lokacji :D

**Comment by Adanos** [comment]
Można to przetestować. ;) Ale powinno wtedy zadziałać.
