### ISSUE TITLE
Wyłączyć debugi.

### ISSUE THREAD

**Issue by CarnageMarkus** [orcwarrior/Czas_Zaplaty#272]
![](http://i.imgur.com/Q5R0lpB.jpg)

**Comment by Adanos** [comment]
Ogólnie z tego co pisał mi Ork, to miało to być tylko do testów.

**Comment by CarnageMarkus** [comment]
No to trzeba pozniej wydadzic :D, tak jak ten debug na obrażenia spadaniem, trochę to pokrywa sie z dialogami

**Comment by Adanos** [comment]
Usunąć również print("Critical!"); z RuneSword_Func.d
