### ISSUE TITLE
Ratford i dialog o magu.

### ISSUE THREAD

**Issue by CarnageMarkus** [orcwarrior/Czas_Zaplaty#274]
Ratford nawet nie był przy magu, a ta opcja pojawia się od razu po rozmowie z Cavalornem. Proponuję dać mu tą opcję dialogową, dopiero jak wróci do obozu.

![](http://i.imgur.com/AZmy9BM.jpg)

**Comment by Adanos** [comment]
Można zamknąć. Powinno działać. :P
