### ISSUE TITLE
Skrzynia w SO.

### ISSUE THREAD

**Issue by CarnageMarkus** [orcwarrior/Czas_Zaplaty#277]
Może zmienić pozycję tej skrzynki, by to normalnie wyglądało?

![](http://i.imgur.com/gKpaEMy.jpg)

**Comment by Adanos** [comment]
Wydaje mi się, że nie jest to potrzebne.

**Comment by CarnageMarkus** [comment]
Jak @Splash97 nie będzie miał nic do roboty to może to zrobić

**Comment by Splash97** [comment]
Spoko, mam to w liście world edit :D Poczekam jeszcze na jakieś bugi i poprawiam co się da. Ale te dropy FPSów są wkurzające xD
