### ISSUE TITLE
Pusty dialog - ENDE.

### ISSUE THREAD

**Issue by CarnageMarkus** [orcwarrior/Czas_Zaplaty#280]
![](http://i.imgur.com/z47Tr4C.jpg)

![](http://i.imgur.com/piZd6SE.jpg)

![](http://i.imgur.com/fdtCthR.jpg)

![](http://i.imgur.com/j88FL8l.jpg)

![](http://i.imgur.com/fz6fseg.jpg)

![](http://i.imgur.com/wg7iod1.jpg)

![](http://i.imgur.com/2I9src9.jpg)

![](http://i.imgur.com/snKo71Z.jpg)

![](http://i.imgur.com/LeHu6NB.jpg)

**Comment by gerard546** [comment]
Trauan teżma opcję ENDE. https://github.com/orcwarrior/Czas_Zaplaty/issues/264

**Comment by Adanos** [comment]
Zmienić tym postaciom typ na ambient.

**Comment by Adanos** [comment]
Jeszcze Herek.
Balam był ok, więc trzeba wycofać zmianę.
