### ISSUE TITLE
Pancerze

### ISSUE THREAD

**Issue by CarnageMarkus** [orcwarrior/Czas_Zaplaty#286]
Od Rodneya można zwyczajnie kupić za silny pancerz, jak na rozdział I. Szczególnie, że z tymi samymi statystykami otrzymujemy początkowy pancerz gildyjny. Proponuje znacząco zmniejszyć staty. 
![](http://i.imgur.com/H5jIYTH.jpg)

**Comment by gerard546** [comment]
e być jednak mniejsze statystyki = mniejsza wartość. Poza tym pancerzem trzeba by podwyższyć statystki lub zrównać z innym Pancerz Aligatora. Przy okazji tak jak pisałem tu: https://github.com/orcwarrior/Czas_Zaplaty/issues/114 można by po wyjściu z Głębi móc naprawić pancerz paladyna.
