### ISSUE TITLE
Lares (dodać zbroje)

### ISSUE THREAD

**Issue by CarnageMarkus** [orcwarrior/Czas_Zaplaty#295]
![](http://i.imgur.com/R0ampov.jpg)

**Comment by Adanos** [comment]
Hmm, powinien dostać tą zbroję. Dodawałem mu. :D

Widzę, że topór ma, ale nie ubrał sobie zbroi.

https://github.com/orcwarrior/Czas_Zaplaty/blob/master/Content/Story/B/B_routins_NC.d#L37-L41
