### ISSUE TITLE
Ostrza dla Aidana - brak sztabek stali

### ISSUE THREAD

**Issue by Adanos** [orcwarrior/Czas_Zaplaty#305]
Dodać do świata gry sztabki stali. Najlepiej handlarzom. Do zadania potrzeba 5 sztabek stali i 10 sztabek żelaza.

**Comment by Splash97** [comment]
Dodam trochę do świata. Dodam także w różnych miejsach jakieś skrzynie, gdzie w niektórych stal też się znajdzie.
