### ISSUE TITLE
Strażnicy atakują bohatera zamiast Znamię

### ISSUE THREAD

**Issue by Adanos** [orcwarrior/Czas_Zaplaty#307]
Strażnicy atakują bohatera zamiast Znamię. Poprawić by atakowali Znamię, a nie bohatera.

**Comment by Adanos** [comment]
Do poprawy.

**Comment by Adanos** [comment]
Wystarczyło zmienić gildię Znamiego na gildię orka wojownika.

**Comment by eralkisz** [comment]
witam mam problem z czas zaplaty mianowicie mam wersie 1.5 nie wyswietlaja sie kluczowe opcie dialogowe 1 strarznicy w misji inwigilacja pisze tylko koniec i u drogiego ktorego mam spic jest tylko ende  i nic by popchnac fabule dalej musialem sciagnac zapic . 2 to rozmowa z radforedm po misji wsparcie nie ma zadnej innej opci dialogowej tylko  nauka oprawiania zwierzyny i nic wiecej ! wczytuje nawet wracam do poprzednich zapisow wykonuje misie raz jeszcze i dalej tak samo ;//
