### ISSUE TITLE
Paul

### ISSUE THREAD

**Issue by gerard546** [orcwarrior/Czas_Zaplaty#82]
Podobno przemieszcza się po całek kolonii. Ja jak na razie spotkałem go jak sobie nigdy nic przechodzi przez obóz rebeliantów.

**Comment by gerard546** [comment]
I jak tam? Coś ruszyło w sprawie tego Paula? Nie chcve go znów spotkać w obozie rebeliantów ;D

**Comment by Adanos** [comment]
:D Nie, będzie trzeba przejrzeć w Spacerze drogę i mu zmienić.

**Comment by Adanos** [comment]
Zmieniłem trasę. Mam nadzieję, że teraz będzie dobrze. :D
