### ISSUE TITLE
Problemy ze sprintem

### ISSUE THREAD

**Issue by Splash97** [orcwarrior/Czas_Zaplaty#84]
Pasek sprintu bardzo często nie kurczy się podczas biegu. Czasem dopiero po ok. 6 sekundach zacznie się kurczyć lub w ogóle się nie kurczy i po pewnym czasie gdy biegniemy sprintem, mod się crashuje.

**Comment by Adanos** [comment]
Pasek sprintu włącza się i wyłącza wtedy, kiedy dwa razy naciśnie się strzałkę do góry.
